apiVersion: v1
kind: ConfigMap
metadata:
  name: oidc-discovery-provider
  namespace: spire
data:
  oidc-discovery-provider.conf: |
    log_level = "INFO"
    domain = "oidc-discovery.naveensrinivasan.com"
    acme {
        directory_url = "https://acme-v02.api.letsencrypt.org/directory"
        cache_dir = "/run/spire"
        tos_accepted = true
        email = "foobar@turris.xyz"
    }
    registration_api {
        socket_path = "/run/spire/sockets/registration.sock"
    }
